with open('.env', 'w', encoding='utf-8') as f:
    f.write('# Arquivo de configuracao do ambiente\n')
    f.write('# Configure as variaveis abaixo conforme seu ambiente MySQL\n\n')
    f.write('# CONFIGURACOES DO MYSQL\n')
    f.write('MYSQL_HOST=localhost\n')
    f.write('MYSQL_PORT=3306\n')
    f.write('MYSQL_DATABASE=sicooperative_db\n')
    f.write('MYSQL_USER=root\n')
    f.write('MYSQL_PASS=sua_senha_aqui\n\n')
    f.write('# CONFIGURACOES DO SPARK\n')
    f.write('SPARK_APP_NAME=SiCooperative-ETL\n')
    f.write('SPARK_MASTER=local[*]\n')
    f.write('SPARK_DRIVER_MEMORY=2g\n')
    f.write('SPARK_EXECUTOR_MEMORY=2g\n\n')
    f.write('# CONFIGURACOES DE OUTPUT\n')
    f.write('OUTPUT_DIR=./output\n')
    f.write('LOG_LEVEL=INFO\n')
    f.write('INCREMENTAL_PROCESSING=true\n')
    f.write('LOOKBACK_DAYS=7\n')
print('Arquivo .env criado com encoding UTF-8 correto!')
